import type { ThemeDefinition } from '@sessionry/plugin-api'

export const defaultTheme: ThemeDefinition = {
  id: 'default',
  name: 'Default',
  description: 'The default Sessionry theme',
  author: 'Sessionry',
  ansi: {
    background: '#0c0c0e',
    foreground: '#d6e1ff',
    cursor: '#ffcb6b',
    selectionBackground: 'rgba(122, 176, 255, 0.24)',
    black: '#2b3144',
    brightBlack: '#66708f',
    red: '#ff7b72',
    brightRed: '#ffa198',
    green: '#97e98b',
    brightGreen: '#bef5b8',
    yellow: '#ffd866',
    brightYellow: '#ffe38f',
    blue: '#7ab0ff',
    brightBlue: '#a4c8ff',
    magenta: '#d2a8ff',
    brightMagenta: '#e4c7ff',
    cyan: '#7ee7ff',
    brightCyan: '#b4f2ff',
    white: '#d6e1ff',
    brightWhite: '#ffffff'
  },
  syntax: {
    keyword: '#d2a8ff',
    function: '#7ab0ff',
    variable: '#d6e1ff',
    type: '#ffd866',
    constant: '#7ee7ff',
    string: '#97e98b',
    number: '#ffd866',
    comment: '#66708f',
    operator: '#7ee7ff',
    punctuation: '#d6e1ff',
    tag: '#ff7b72',
    attribute: '#7ab0ff',
    property: '#d6e1ff',
    class: '#ffd866',
    interface: '#ffd866',
    namespace: '#ffd866',
    parameter: '#d6e1ff',
    decorator: '#d2a8ff',
    regexp: '#7ee7ff',
    escape: '#7ee7ff',
    link: '#7ab0ff',
    heading: '#7ab0ff',
    emphasis: '#d6e1ff',
    strong: '#d6e1ff',
    deleted: '#ff7b72',
    inserted: '#97e98b',
    invalid: '#ff7b72'
  }
}
