import type { ThemeDefinition } from '@sessionry/plugin-api';

export const draculaTheme: ThemeDefinition = {
  id: 'dracula',
  name: 'Dracula',
  description: 'A dark theme for those who live in the night',
  author: 'Dracula Theme',
  ansi: {
    background: '#282a36',
    foreground: '#f8f8f2',
    cursor: '#f8f8f2',
    selectionBackground: 'rgba(68, 71, 90, 0.7)',
    black: '#21222c',
    brightBlack: '#6272a4',
    red: '#ff5555',
    brightRed: '#ff6e6e',
    green: '#50fa7b',
    brightGreen: '#69ff94',
    yellow: '#f1fa8c',
    brightYellow: '#ffffa5',
    blue: '#bd93f9',
    brightBlue: '#d6acff',
    magenta: '#ff79c6',
    brightMagenta: '#ff92df',
    cyan: '#8be9fd',
    brightCyan: '#a4ffff',
    white: '#f8f8f2',
    brightWhite: '#ffffff'
  },
  syntax: {
    keyword: '#ff79c6',
    function: '#bd93f9',
    variable: '#f8f8f2',
    type: '#f1fa8c',
    constant: '#8be9fd',
    string: '#50fa7b',
    number: '#f1fa8c',
    comment: '#6272a4',
    operator: '#8be9fd',
    punctuation: '#f8f8f2',
    tag: '#ff5555',
    attribute: '#bd93f9',
    property: '#f8f8f2',
    class: '#f1fa8c',
    interface: '#f1fa8c',
    namespace: '#f1fa8c',
    parameter: '#f8f8f2',
    decorator: '#ff79c6',
    regexp: '#8be9fd',
    escape: '#8be9fd',
    link: '#bd93f9',
    heading: '#bd93f9',
    emphasis: '#f8f8f2',
    strong: '#f8f8f2',
    deleted: '#ff5555',
    inserted: '#50fa7b',
    invalid: '#ff5555'
  }
};
